[build]
    functions = "netlify/functions"
    publish = "public"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[functions]
  included_files = ["netlify/functions/key.pem", "netlify/functions/cert.pem"]
  external_node_modules = ["pug"]